-- MySQL Script generated by MySQL Workbench
-- Thu Jul  7 20:01:35 2022
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema escolas
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `escolas` ;

-- -----------------------------------------------------
-- Schema escolas
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `escolas` DEFAULT CHARACTER SET utf8 ;
USE `escolas` ;

-- -----------------------------------------------------
-- Table `escolas`.`responsavel_financeiro`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `escolas`.`responsavel_financeiro` (
  `codigo_responsavel_financeiro` INT NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(50) NOT NULL,
  `cpf` CHAR(14) NOT NULL,
  PRIMARY KEY (`codigo_responsavel_financeiro`),
  UNIQUE INDEX `cpf_UNIQUE` (`cpf` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `escolas`.`turmas`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `escolas`.`turmas` (
  `codigo_turma` INT NOT NULL,
  `filial` TINYINT UNSIGNED NOT NULL,
  `turno` CHAR(1) NOT NULL,
  PRIMARY KEY (`codigo_turma`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `escolas`.`alunos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `escolas`.`alunos` (
  `ra` INT UNSIGNED NOT NULL,
  `nome` VARCHAR(50) NOT NULL,
  `genero` CHAR(1) NULL,
  `rua` VARCHAR(60) NOT NULL,
  `numero` VARCHAR(10) NOT NULL,
  `bairro` VARCHAR(50) NOT NULL,
  `cidade` VARCHAR(40) NOT NULL,
  `codigo_responsavel_financeiro` INT NULL,
  `codigo_turma` INT NOT NULL,
  PRIMARY KEY (`ra`),
  INDEX `fk_responsavel_financeiro` (`codigo_responsavel_financeiro` ASC) INVISIBLE,
  INDEX `fk_alunos_turmas` (`codigo_turma` ASC) VISIBLE,
  CONSTRAINT `fk_responsavel_financeiro`
    FOREIGN KEY (`codigo_responsavel_financeiro`)
    REFERENCES `escolas`.`responsavel_financeiro` (`codigo_responsavel_financeiro`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_alunos_turmas1`
    FOREIGN KEY (`codigo_turma`)
    REFERENCES `escolas`.`turmas` (`codigo_turma`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `escolas`.`professores`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `escolas`.`professores` (
  `chapa` VARCHAR(8) NOT NULL,
  `nome` VARCHAR(50) NOT NULL,
  PRIMARY KEY (`chapa`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `escolas`.`especialidades`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `escolas`.`especialidades` (
  `codigo_especialidade` SMALLINT UNSIGNED NOT NULL AUTO_INCREMENT,
  `titulacao` VARCHAR(30) NOT NULL,
  PRIMARY KEY (`codigo_especialidade`),
  UNIQUE INDEX `titulacao_UNIQUE` (`titulacao` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `escolas`.`professores_especialidades`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `escolas`.`professores_especialidades` (
  `professores_chapa` VARCHAR(8) NOT NULL,
  `especialidades_codigo_especialidade` SMALLINT UNSIGNED NOT NULL,
  PRIMARY KEY (`professores_chapa`, `especialidades_codigo_especialidade`),
  INDEX `fk_professores_has_especialidades_especialidades1_idx` (`especialidades_codigo_especialidade` ASC) VISIBLE,
  INDEX `fk_professores_has_especialidades_professores1_idx` (`professores_chapa` ASC) VISIBLE,
  CONSTRAINT `fk_professores_has_especialidades_professores1`
    FOREIGN KEY (`professores_chapa`)
    REFERENCES `escolas`.`professores` (`chapa`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_professores_has_especialidades_especialidades1`
    FOREIGN KEY (`especialidades_codigo_especialidade`)
    REFERENCES `escolas`.`especialidades` (`codigo_especialidade`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `escolas`.`disciplina`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `escolas`.`disciplina` (
  `codigo_turma` INT NOT NULL,
  `chapa_professor` VARCHAR(8) NOT NULL,
  `sala` CHAR(3) NOT NULL,
  PRIMARY KEY (`codigo_turma`, `chapa_professor`),
  INDEX `fk_turmas_has_professores_professores1_idx` (`chapa_professor` ASC) VISIBLE,
  INDEX `fk_turmas_has_professores_turmas1_idx` (`codigo_turma` ASC) VISIBLE,
  CONSTRAINT `fk_turmas_has_professores_turmas1`
    FOREIGN KEY (`codigo_turma`)
    REFERENCES `escolas`.`turmas` (`codigo_turma`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_turmas_has_professores_professores1`
    FOREIGN KEY (`chapa_professor`)
    REFERENCES `escolas`.`professores` (`chapa`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
